### ISSUE TITLE
page link issue

### ISSUE THREAD

**Issue by MksRasp** [glennmckechnie/weewx-wxobs#8]
I have installed the latest version of weewx-wxobs v0.7.6 and it is working greate but I could not figure out how to link to wxobs php page from weewx main page.
what I do now is having two bookmarks for weewx and wxobs

wxobs page at (192.*.*.*/weewx/wxobs/index.php) and from here I can go back to main page of weewx by clicking on (❰ Current Conditions)

weewx page (192.*.*.*/weewx/index.html) here I can not find away to go to wxobs page.

is this by design or am I missing something?

**Comment by glennmckechnie** [comment]
You're missing my missing instructions. Ooops. ;-)

The link from the Seasons page to wxobs has to be done manually. The return link is via the Current conditions link (that you are using.)
I thought I had this documented in point 6 of the README instructions but it certainly isn't there.

I've now revamped that page with those missing instructions. Let me know if they need clarifying.

**Comment by MksRasp** [comment]
Tried the new instruction but it did not work, weewx was generating this error

***
ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx/skins/Seasons/index.html.tmpl failed with exception '<class 'ModuleNotFoundError'>'
ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Seasons/index.html.tmpl
ERROR weewx.cheetahgenerator: **** Reason: No module named 'dateutil'
ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 348, in generate
ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_Seasons_index_html_tmpl_1648877730_7254903_10243.py", line 223, in respond
ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1685, in _handleCheetahInclude
ERROR weewx.cheetahgenerator: ****      nestedTemplateClass = compiler.compile(source=source,
ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 824, in compile
ERROR weewx.cheetahgenerator: ****      exec(co, mod.__dict__)
ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_wxobs_links_inc.py", line 27, in <module>
ERROR weewx.cheetahgenerator: ****  ModuleNotFoundError: No module named 'dateutil'
***

with the help of google earch about this error the search results suggested to install this model:

sudo pip3 install python-dateutil

now wxobs is working with no issue.

I wanted wxobs to open on the same page as weewx so I edited links.inc and changed thes lines from:

submitDate=Show+records" target="_blank">Daily Summary
submitDate=Show+records" target="_blank">todays data.

to:

submitDate=Show+records" target="_self">Daily Summary
submitDate=Show+records" target="_self">todays data

--------------------------------------------------------------------
the folder structure of wxobs on my machine:

"font"-----------------Folder
"datepicker.css"-------File
"datepicker.js.tmpl"---File
"index.php.tmpl"-------File
"links.inc"------------File
"seasons.css"----------File
"skin.conf"------------File
"standard.js"----------File
"weewx.css"------------File
"wxobs.css"------------File
"wxobs.inc"------------File


these are missing

"lang"---------------Folder
"datepicker.js"------File
"deltaT.php"---------File
"standard.css"-------File

did wxobs installed correctly?

--------------------------------------------------------------------
I appreciate your help, support and the time you have spent creating this gem.

using wxobs have uncovered some bad timing error in my weewx database that I imported 4 years ago, I was not aware of it.

**Comment by glennmckechnie** [comment]
" No module named 'dateutil' " 
Hmmm. That error rings a bell and looking through previous discussions I find a private exchange where that came up before. The conclusion was that it was redundant so I'll finish the job and actually remove it this time. Not sure why it was there, possibly needed in a previous weewx version? Don't know; but it runs fine without it.  Modded the file to remove that line.

datepicker.js has been replaced with datepicker.js.tmpl which is generated via the [[ToDate]] section. it has the new $gettext lang options within it. datepicker.js now removed from the repo.

lang has been left out of the last update - another Mea culpa. Updated the installer to include the lang directory.

deltaT.php is not needed for a working install. I probably used that for testing at the start, it's still useful if you want to do some sanity checks or oddball calcs - only useful if you use delta-T though. Keeping it in the repo, won't be installed though. 

standard.css, Old. That's going back to before Seasons was even named! Now removed from the repo.
same logic for standard.js. Also removed.

I've updated the installer to include the lang directory.

If you download from master you'll get all these updates. There is also a pre-release you could use. I forgot to mention that I altered links.inc too as the one that you were using was unique to my install, the master is correct.

If you could do a fresh install and see if it all installs and performs correctly I'd appreciate it. If it works for you I'll update the pre-release to an actual release!

> I appreciate your help, support and the time you have spent creating this gem.

Not a problem. 
And I appreciate the feedback. Without that, those errors would remain. You've improved it. 

> using wxobs have uncovered some bad timing error in my weewx database that I imported 4 years ago, I was not aware of it.

Interesting. Not a use that I would have picked for it :-) But I'll take it!

**Comment by MksRasp** [comment]
1-uninstalled wxobs and manually cleaned the traces
2-install.... but failed with these error:

sudo wee_extension --install weewx-wxobs.zip
Request to install 'weewx-wxobs.zip'
Extracting from zip archive weewx-wxobs.zip
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 92, in <module>
    main()
  File "/usr/share/weewx/wee_extension", line 84, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 130, in install_extension
    self.install_from_dir(extension_dir)
  File "/usr/share/weewx/weecfg/extension.py", line 183, in install_from_dir
    shutil.copy(source_path, destination_path)
  File "/usr/lib/python3.9/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/weewx-wxobs-master/skins/wxobs/standard.js'



**edited "install.py" and removed the line for "standard.js" and installer worked this time**

**Comment by glennmckechnie** [comment]
Argh.

Thanks. Got it, fixed.
Perfect debugging too.

While I'm in there.  I added notes to the header section in links.inc to briefly document your __blank_ to __self_ change.
Now... re-tested (as LAST step! and then again) and now pushed.

Bumped to New release status - v0.7.7

**Comment by MksRasp** [comment]
Now everything works perfectly.
Thank you very much.
